.github/actions/bootstrap/action.yml, .github/workflows/post-merge.yml, .github/workflows/pre-merge.yml
Cache adjustments:
- Deleting the cache will always succeed.
- The cache will only be saved if there was no exact match during restore (i.e., using `key` rather than `restore-keys`) - this will shorten the run time and save space.
- Improved parameter descriptions have been added, showing the steps needed to use the cache as efficiently as possible.
=> chore: Cache adjustments

dev-version-update/action.yml, scripts/custom-version-tag.sh, scripts/version-tag-param.sh, scripts/version-tag.sh
=> chore: standardize bot user and password

.github/workflows/post-merge-orch-ci.yml, .github/workflows/post-merge.yml
=> chore: move ossf publish to security tab

.github/workflows/post-merge.yml
=> fix: solve ossf 500 error

.github/workflows/pre-merge-orch-ci.yml, .github/workflows/pre-merge.yml
=> feat: upload trivy results to security tab

.github/actions/bootstrap/action.yml
=> fix: remove typos from npm bootstrap

.github/workflows/pre-merge.yml
Provide the trivy.yaml configuration to the Docker image trivy scanner.
=> feat: Pass trivy-config to docker image scan

.github/workflows/pre-merge.yml
Print the remaining high/critical tasks to be fixed in the CI pipeline so that developer need not filter it out manually from the complete trivy scan report of previous steps
=> feat: Print the remaining high/critical tasks to be fixed

.github/workflows/build-documentation.yml, .github/workflows/publish-documentation.yml
Changes template repository to `edge-manage-docs`
=> Updates template repo to edge-manage-docs

.github/workflows/apporch-go-fuzz.yml, .github/workflows/build-documentation.yml, .github/workflows/post-merge-orch-ci.yml, .github/workflows/pre-merge-orch-ci.yml, .github/workflows/test_bootstrap.yml
=> chore: fix ossf findings

.github/workflows/pre-merge.yml
=> feat: use zizmor for workflows scan

.github/workflows/post-merge.yml
=> fix: allow token write for version tag

.github/workflows/post-merge-orch-ci.yml
=> fix: sync permissions

.github/workflows/pre-merge.yml
=> cleanup unwanted installed tools/packages to fix disk space issue

.github/workflows/pre-merge.yml, verify-branch-name/action.yml
=> fix: solve typo and set correct env location

.github/workflows/post-merge-orch-ci.yml, .github/workflows/post-merge.yml
=> chore: upload results from main to security tab

.github/workflows/publish-documentation.yml
Support version switcher dropdown menu for multiple documentation versions.
When multiple documentation branches are built, the documentation should present a dropdown menu which allows users to select a specific version.
None.
Reusing similar technique from Innersource.
=> Support version switcher dropdown menu for multiple doc versions

.github/workflows/post-merge.yml
=> post merge - removed unwanted packages

.github/workflows/publish-documentation.yml
This PR will modify the documentation version in the drop-down menu to display `dev` instead of `main`
=> Replace documentation version `main` with `dev`.

.github/workflows/pre-merge.yml
Remove refs from pre-merge as it's crashing PRs from forks
=> fix: remove refs from workflows

.github/workflows/post-merge.yml
=> fix: skip images with none tag or repository

gitleaks_baselines/gitleaks-edge-manageability-framework.json
=> chore: update gitleaks baseline

.github/workflows/post-merge.yml, .github/workflows/pre-merge.yml
fix: move image filtering to image list step
Image scan job fails for images with none:none tag
=> fix: move image filtering to image list step

.github/actions/security/bandit/action.yml, .github/workflows/post-merge.yml
=> fix: post merge should not fail on bandit findings

.github/workflows/post-merge.yml
=> feat: add upload to ghcr.io

.github/CODEOWNERS
=> chore: cleanup codeowners

.github/workflows/pre-merge.yml
=> chore: skip docker/helm push for dependabot

.gitleaks.toml, gitleaks_baselines/gitleaks-infra-core.json
Mark gitleaks issues as false positives in infra-core
=> Infra core baseline

.github/workflows/pre-merge.yml, gitleaks_baselines/gitleaks-inventory.json
=> add baseline for inventory

.github/workflows/publish-documentation.yml
Commenting out these lines made scenescape docs fail so adding them conditionally based on workflow output to enable them just in failing repos.
=> Fix replacing main with dev for scenescape

.github/workflows/post-merge.yml, .github/workflows/pre-merge.yml
=> chore: set temp workaround for checkout

.github/workflows/build-documentation.yml, .github/workflows/publish-documentation.yml
Changing how conf files are detected. Previously exclude was added to non-existing file and didn't have any effect on sphinx build
Copied functionality to publish-documentation as well
=> Fix exclude pattern in documentation workflows

.github/workflows/post-merge.yml
Fix for "Resource not accessible by integration" in post-merge
Observed issue:
Uploading code scanning results
Processing sarif files: ["scorecard-results-orch-ci.sarif"]
Validating scorecard-results-orch-ci.sarif
Warning: 'no file associated with this alert' is not a valid URI in 'instance.runs[0].results[0].locations[0].physicalLocation.artifactLocation.uri'.
Warning: 'no file associated with this alert' is not a valid URI in 'instance.runs[2].results[0].locations[0].physicalLocation.artifactLocation.uri'.
Warning: 'no file associated with this alert' is not a valid URI in 'instance.runs[2].results[1].locations[0].physicalLocation.artifactLocation.uri'.
Warning: 'no file associated with this alert' is not a valid URI in 'instance.runs[2].results[2].locations[0].physicalLocation.artifactL …
=> Fix for "Resource not accessible by integration" in post-merge

.github/workflows/post-merge.yml
Remove fuzzing from Scorecard sarif file
=> Remove fuzzing from Scorecard sarif file
